//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArkLens.Resources.Elements {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Emojis {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Emojis() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArkLens.Resources.Elements.Emojis", typeof(Emojis).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ♀️.
        /// </summary>
        public static string Gender_Female {
            get {
                return ResourceManager.GetString("Gender.Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ♂️.
        /// </summary>
        public static string Gender_Male {
            get {
                return ResourceManager.GetString("Gender.Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🧔.
        /// </summary>
        public static string Race_Dwarf {
            get {
                return ResourceManager.GetString("Race.Dwarf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🧝.
        /// </summary>
        public static string Race_Elf {
            get {
                return ResourceManager.GetString("Race.Elf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🧑.
        /// </summary>
        public static string Race_Human {
            get {
                return ResourceManager.GetString("Race.Human", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🦊.
        /// </summary>
        public static string Race_Kitsune {
            get {
                return ResourceManager.GetString("Race.Kitsune", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ♉.
        /// </summary>
        public static string Race_Minas {
            get {
                return ResourceManager.GetString("Race.Minas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🦎.
        /// </summary>
        public static string Race_Serpent {
            get {
                return ResourceManager.GetString("Race.Serpent", resourceCulture);
            }
        }
    }
}
